# Generated by Django 3.1.5 on 2021-02-24 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=3000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('author', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEdited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('city', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('relationships', models.CharField(default='Не указано', max_length=30)),
                ('status', models.CharField(default='Client', max_length=30)),
                ('clientid', models.TextField(default='Z')),
                ('phone', models.CharField(default='z', max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('changes_is_moderated', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=150)),
                ('comment_author', models.CharField(default='User', max_length=30)),
                ('comment_authorid', models.TextField(default='z')),
                ('comment_published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publicationcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('city', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('relationships', models.CharField(default='Не указано', max_length=30)),
                ('status', models.CharField(default='Client', max_length=30)),
                ('iin', models.CharField(default='x', max_length=12)),
                ('balance', models.IntegerField(default=0)),
                ('is_moderated', models.BooleanField(default=False)),
                ('changes_is_moderated', models.BooleanField(default=False)),
                ('phone', models.CharField(default='z', max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
