# Generated by Django 3.1.5 on 2021-02-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210225_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
