# Generated by Django 3.1.5 on 2021-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientid',
            field=models.TextField(default='Z'),
        ),
    ]
