# Generated by Django 3.1.5 on 2021-02-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='reciever_iin',
            field=models.CharField(db_index=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='reciever_number',
            field=models.CharField(db_index=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='sender_iin',
            field=models.CharField(db_index=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='sender_number',
            field=models.CharField(db_index=True, default=0, max_length=30),
            preserve_default=False,
        ),
    ]
