# Generated by Django 3.1.5 on 2021-02-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210227_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='reciever_number',
            new_name='reciever_phone',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='sender_number',
            new_name='sender_phone',
        ),
    ]
